version: '2'
services:
    app:
        build: docker/php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
            - "DB_DATABASE=gym"
            - "DB_USERNAME=rayuser"
            - "DB_PASSWORD=raypass"

    web:
        build: docker/nginx
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - 8008:80

    db:
        image: mysql:5.7.24
        volumes:
            - dbgym:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=gym"
            - "MYSQL_USER=rayuser"
            - "MYSQL_PASSWORD=raypass"
            - "MYSQL_ROOT_PASSWORD=rootpassword"
        ports:
            - "33068:3306"

volumes:
    dbgym: